[versions]
android-minSdk = "24"
android-compileSdk = "36"
android-targetSdk = "36"
appVersionCode = "10"
appVersionName = "1.0.9"

agp = "8.13.2"
kotlin = "2.3.0"
compose = "1.10.0"
vanniktechMavenPublish = "0.36.0"
material3-adaptive = "1.2.0"
kotlinx-datetime = "0.7.1"
androidx-activityCompose = "1.12.2"
androidx-navigation = "2.9.6"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

# UI Components
cmp-datetime-picker = { module = "io.github.darkokoa:datetime-wheel-picker", version = "1.1.0" }
cmp-constraintlayout = { module = "tech.annexflow.compose:constraintlayout-compose-multiplatform", version = "0.6.1" }
cmp-shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version = "1.3.3" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version = "3.3.0" }
coil-network = { module = "io.coil-kt.coil3:coil-network-ktor3", version = "3.3.0" }

# Material3 Adaptive bundle
material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "material3-adaptive" }
material3-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "material3-adaptive" }
material3-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "material3-adaptive" }

# Demo app dependencies
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }